###############################################################################
### General Configuration
# -----------------------------------------------------------------------------
# - Borders, decoração, animações
# - Pseudotiling, master layout e misc
###############################################################################

general {
    border_size = 2
    col.active_border = rgba(00ccffee)
    col.inactive_border = rgba(1e1e2eaa)
}

decoration {
    rounding = 14
    rounding_power = 3.0

    blur {
        enabled = true
        size = 6
        passes = 2
        new_optimizations = true
    }

    shadow {
        enabled = false
    }
}

animations {
    enabled = yes
    bezier = smooth, 0.25, 0.1, 0.25, 1
    animation = windows, 1, 4, smooth
    animation = windowsIn, 1, 4, smooth, popin 80%
    animation = windowsOut, 1, 2, smooth
    animation = fade, 1, 3, smooth
    animation = workspaces, 1, 4, smooth
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
    animate_manual_resizes = false
}