###############################################################################
### Input Configuration
# -----------------------------------------------------------------------------
# - Layout e variante de teclado
###############################################################################

input {
    kb_layout = br
    kb_variant = abnt2
}