###############################################################################
### Permissions
# -----------------------------------------------------------------------------
# - Configura permissões para screencopy, plugins e apps
# - Alterações requerem reinício do Hyprland
###############################################################################

cursor {
    inactive_timeout = 3
    no_hardware_cursors = true
}

permission = /usr/(bin|local/bin)/grim, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow