background {
    blur_passes = 4
    blur_size = 10
}

# Clock (principal)
label {
    text = cmd[update:1000] echo "$(date +%H:%M)"
    font_size = 96
    color = rgba(0, 255, 255, 0.95)

    position = 0, 120
    halign = center
    valign = center
}

# Date
label {
    text = cmd[update:60000] echo "$(date +'%A, %d %B')"
    font_size = 28
    color = rgba(0, 255, 255, 0.55)

    position = 0, 60
    halign = center
    valign = center
}

# User
label {
    text = Emanoel
    font_size = 18
    color = rgba(0, 255, 255, 0.6)

    position = 0, -40
    halign = center
    valign = center
}

# Input field (estilo GNOME + neon)
input-field {
    size = 260, 45
    outline_thickness = 2

    outer_color = rgba(0, 255, 255, 0.5)
    inner_color = rgba(0, 10, 20, 0.5)
    font_color = rgba(0, 255, 255, 0.9)

    fade_on_empty = true

    position = 0, -90
    halign = center
    valign = center
}

# Status discreto
label {
    text = AUTHENTICATION REQUIRED
    font_size = 16
    color = rgba(0, 255, 255, 0.35)

    position = 0, -140
    halign = center
    valign = center
}